### PR TITLE
Add support for Nokogiri 1.7.x

### PR DESCRIPTION
**Pull request by phlipper**
This PR relaxes the version requirement of Nokogiri to support 1.7.x which has recently been released.

### CODE REVIEW

**Comment by phlipper** [comment]
The JRuby build appears to be failing due to an unrelated error.

**Comment by Mange** [comment]
Thank you! :heart:

**Comment by Mange** [comment]
I'm ready to give up on JRuby until someone want to help me to get it to work, so please add it as an allowed failure in the Travis config and I'll merge this. I'd also like it if you could add a line to the Changelog about this change.

**Comment by phlipper** [comment]
@Mange feedback addressed, thank you very much

**Comment by Mange** [comment]
Thanks again!

**Comment by Mange** [comment]
I just released version 3.2.1 with this fix included. Thank you for your contribution.

**Pull request merged**
