### PR TITLE
Add support for document fragments

### PR DESCRIPTION
**Pull request by andfx**
As suggested in #70: Roadie should be able to handle document fragments as well. This pull request adds a <tt>DocumentFragment</tt> class to handle fragments.

Regards

### CODE REVIEW

**Comment by Mange** [comment]
Thanks! Some feedback:

1. I like Liskov's Substitution Principle, and this subclass violates it: A `DocumentFragment` is not a `Document`.
  * One could argue that a `Document` is a `DocumentFragment` - it just adds some more behavior on top.
  * I'd prefer a `DocumentBase`, with `protected` instance methods to override. Mark it as `@abstract` and `@api private` in a comment, too.
2. We need to figure out a way to share tests somehow. Shared examples are probably the way to go, but I'm still unsure on how to structure them. I could take that over if you don't come up with any ideas.
3.   This needs to be documented in the `README` as well. A paragraph should be enough; something along the lines of this:
    
    > If you don't want to transform an entire document (with `<head>` and `<body>`), you can use `DocumentFragment` instead of `Document`. A `DocumentFragment` represents a contained chunk of markup, without any implications of it being a complete document. Doctype and structure elements will not be inserted.
    >
    >     Code example here.

Let me know if you want me to take over at some point. You don't owe me anything. :wink:

**Comment by andfx** [comment]
Great feedback, thanks!

I added the `DocumentBase` with an abstract `#transform`method and extended the README. Feel free to take over from here!

Thanks!

**Comment by andfx** [comment]
Hi,

I also had to add a workaround for JRuby in the DocumentFragment class, due to sparklemotion/nokogiri#832.

Regards

**Comment by Mange** [comment]
Time really flies... I got another PR for this same feature, which reminded me. I chose to implement it myself in a slightly different way in #147. I'd appreciate if you were able to test that variant and come with some feedback.

**Pull request closed without merging**
